# Generated by Django 3.1.2 on 2022-04-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared')], max_length=200, null=True)),
                ('Paid_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('DateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('AddedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('refferel', 'Refferel')], default='none', max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Contact', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Loacation', models.CharField(blank=True, max_length=200, null=True)),
                ('DateAdded', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('none', 'None')], default='none', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_Of_Birth', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, choices=[('on hold', 'On Hold'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], max_length=200, null=True)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('Address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gettreat.location')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettreat.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctors_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('DepartmentName', models.ManyToManyField(to='gettreat.Departments')),
                ('Hospital_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gettreat.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Added_Date', models.DateField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettreat.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Offered', models.CharField(blank=True, max_length=200, null=True)),
                ('Departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gettreat.departments')),
                ('Hospital_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gettreat.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='Hospital_Loacation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gettreat.location'),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('AddedDate', models.DateField(auto_now_add=True)),
                ('Hospital_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettreat.hospital')),
            ],
        ),
    ]
