# Generated by Django 3.1.2 on 2022-07-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_services',
            old_name='Departments',
            new_name='department',
        ),
    ]
