# Generated by Django 3.1.2 on 2022-04-24 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_doctors',
            name='Email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='our_doctors',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='our_doctors',
            name='Registered_Date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 24, 15, 38, 2, 388050, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
