# Generated by Django 3.1.2 on 2022-04-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0002_auto_20220415_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_patients',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=200, null=True),
        ),
    ]
