# Generated by Django 3.1.2 on 2022-04-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0002_auto_20220424_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_doctors',
            old_name='DepartmentName',
            new_name='Department_Name',
        ),
    ]
