# Generated by Django 3.1.2 on 2022-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0003_auto_20220424_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_doctors',
            name='status',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temperory', 'Temperory')], default='temperory', max_length=200, null=True),
        ),
    ]
