# Generated by Django 3.1.2 on 2022-04-14 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0004_auto_20220415_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_patients',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 4, 14, 22, 1, 59, 678087, tzinfo=utc), upload_to='patients'),
            preserve_default=False,
        ),
    ]
