# Generated by Django 3.1.2 on 2022-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0004_our_doctors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('pending', 'Pending'), ('picked', 'Picked'), ('admitted', 'Admitted')], default='pending', max_length=200),
        ),
    ]
