# Generated by Django 3.1.2 on 2022-04-15 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0005_our_patients_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gettreat.location'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
