# Generated by Django 3.1.2 on 2022-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0006_auto_20220415_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('declined', 'Declined')], max_length=200, null=True),
        ),
    ]
