# Generated by Django 3.1.2 on 2022-04-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0007_auto_20220415_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='phone',
            new_name='Immediete_phone',
        ),
    ]
