# Generated by Django 3.1.2 on 2022-04-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0008_auto_20220415_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=200, null=True),
        ),
    ]
