# Generated by Django 3.1.2 on 2022-04-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettreat', '0010_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('pending', 'Pending'), ('picked', 'Picked')], default='pending', max_length=200),
        ),
    ]
